services:
  - type: web
    name: evoshield-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '["https://evoshield-waf.vercel.app","https://frontend-one-ivory-daqy44n4d5.vercel.app","http://localhost:5173"]'
      - key: ALERT_FROM_EMAIL
        sync: false
      - key: ALERT_APP_PASSWORD
        sync: false
      - key: ALERT_TO_EMAIL
        sync: false
